Neos:
  Neos:
#    nodeTypes:
#      groups:
#        projects:
#          position: 'after plugins'
#          label: Projects
    fusion:
      autoInclude:
        MIWeb.Neos.NodeTypes: true
    userInterface:
      translation:
        autoInclude:
          MIWeb.Neos.NodeTypes:
            - 'NodeTypes/*'